# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         TheSchwartz-Worker-SendEmail
version:      1.00
version_from: lib/TheSchwartz/Worker/SendEmail.pm
installdirs:  site
requires:
    Net::Cmd:                      0
    Net::Config:                   0
    Net::DNS:                      0
    Net::SMTP:                     0
    Storable:                      0
    TheSchwartz::Worker:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
